package domini;

public enum ConversioUnitats
{
    RAD_GRAUS, GRAUS_RAD, KM_MILLA, MILLA_KM, KG_LLIURA, LLIURA_KG, LITRE_GALO,
    GALO_LITRE, CELSIUS_KELVIN, KELVIN_CELSIUS, KELVIN_FAHRENHEIT,
    FAHRENHEIT_KELVIN, FAHRENHEIT_CELSIUS, CELSIU_FAHRENHEIT, KM2_HECATAREA,
    HECTAREA_KM2, KMH_MILLAH, MILLAH_KMH;
}
