package domini;

public enum OperacioFull
{
    EXTREU_HOROSCOP, EXTREU_ANY, EXTREU_MES, EXTREU_DIA, EXTREU_DIA_SETMANA,
    EXECUTA_OPERACIO_ARITMETICA_UNARIA, EXECUTA_FUNCIO_ESTADISTICA,
    TRUNCA_NUMERO, CONVERTEIX_UNITATS, EXTREU_LONGITUD_TEXT,
    CERCA_OCURRENCIES, CONVERTEIX_MAJUSCULES, CONVERTEIX_MINUSCULES,
    TRANSPOSA, REEMPLACA, ORDENA, MODIFICA_CELA,
    AFEGEIX_COLUMNA, AFEGEIX_FILA, ELIMINA_COLUMNA, ELIMINA_FILA,
    MOU_BLOC, COPIA_BLOC, BUIDA_BLOC;
}
